"""
Application Constants
Centralized constants used throughout the application.
"""

# Application Information
APP_NAME = "YouTube Bot Video Extractor"
APP_VERSION = "1.0.0"
APP_AUTHOR = "Mohit Narayan"
APP_LICENSE = "MIT"

# Database
DATABASE_VERSION = 1
DEFAULT_DATABASE_PATH = "data/app.db"

# Video Processing
MAX_RETRIES = 3
RETRY_DELAY_SECONDS = 5
API_TIMEOUT_SECONDS = 30
DEFAULT_VIDEO_QUALITY = "best"
DEFAULT_VIDEO_FORMAT = "mp4"
MAX_FILESIZE_MB = 2048

# Monitoring
DEFAULT_CHECK_INTERVAL_MINUTES = 10
DEFAULT_LOOKBACK_HOURS = 24
MAX_VIDEOS_PER_CHECK = 5

# Active Hours
DEFAULT_ACTIVE_START = "10:00"
DEFAULT_ACTIVE_END = "22:00"

# YouTube API
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
YOUTUBE_SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.readonly",
    "https://www.googleapis.com/auth/youtube.force-ssl"
]

# YouTube API Quota Costs (per operation)
QUOTA_SEARCH = 100
QUOTA_VIDEO_LIST = 1
QUOTA_VIDEO_INSERT = 1600
QUOTA_THUMBNAIL_SET = 50
DAILY_QUOTA_LIMIT = 10000
QUOTA_WARNING_THRESHOLD = 0.8  # Warn at 80%
QUOTA_PAUSE_THRESHOLD = 0.95   # Pause at 95%

# Video Status
STATUS_PENDING = "pending"
STATUS_DOWNLOADING = "downloading"
STATUS_DOWNLOADED = "downloaded"
STATUS_UPLOADING = "uploading"
STATUS_COMPLETED = "completed"
STATUS_FAILED = "failed"

# Log Levels
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

# Logging
MAX_LOG_SIZE_MB = 10
LOG_BACKUP_COUNT = 5
DEFAULT_LOG_FILE = "logs/app.log"

# Directories
DEFAULT_DOWNLOAD_DIR = "downloads"
DEFAULT_LOGS_DIR = "logs"
DEFAULT_DATA_DIR = "data"

# File Cleanup
DEFAULT_KEEP_DAYS = 7
DEFAULT_MAX_STORAGE_GB = 50

# GUI
SYSTEM_TRAY_ICON_IDLE = "🟢"
SYSTEM_TRAY_ICON_DOWNLOADING = "🔵"
SYSTEM_TRAY_ICON_UPLOADING = "🟡"
SYSTEM_TRAY_ICON_ERROR = "🔴"
SYSTEM_TRAY_ICON_PAUSED = "⚫"

# Notifications
NOTIFICATION_DURATION_MS = 5000

# Performance
MAX_CONCURRENT_DOWNLOADS = 2
MAX_CONCURRENT_UPLOADS = 1
DOWNLOAD_CHUNK_SIZE_KB = 1024

# YouTube Categories (https://developers.google.com/youtube/v3/docs/videoCategories/list)
YOUTUBE_CATEGORY_FILM_ANIMATION = "1"
YOUTUBE_CATEGORY_AUTOS_VEHICLES = "2"
YOUTUBE_CATEGORY_MUSIC = "10"
YOUTUBE_CATEGORY_PETS_ANIMALS = "15"
YOUTUBE_CATEGORY_SPORTS = "17"
YOUTUBE_CATEGORY_TRAVEL_EVENTS = "19"
YOUTUBE_CATEGORY_GAMING = "20"
YOUTUBE_CATEGORY_PEOPLE_BLOGS = "22"
YOUTUBE_CATEGORY_COMEDY = "23"
YOUTUBE_CATEGORY_ENTERTAINMENT = "24"
YOUTUBE_CATEGORY_NEWS_POLITICS = "25"
YOUTUBE_CATEGORY_HOWTO_STYLE = "26"
YOUTUBE_CATEGORY_EDUCATION = "27"
YOUTUBE_CATEGORY_SCIENCE_TECHNOLOGY = "28"

# Privacy Status
PRIVACY_PUBLIC = "public"
PRIVACY_PRIVATE = "private"
PRIVACY_UNLISTED = "unlisted"
